bedroom_choices = {
    "1": 1, 
    "2": 2, 
    "3": 3, 
    "4": 4, 
    "5": 5, 
    "6": 6, 
    "7": 7, 
    "8": 8, 
    "9": 9, 
    "10": 10
}

price_choices = {
    "100000": "€100,000",
    "200000": "€200,000",
    "300000": "€300,000",
    "400000": "€400,000",
    "500000": "€500,000",
    "600000": "€600,000",
    "700000": "€700,000",
    "800000": "€800,000",
    "900000": "€900,000",
    "1000000": "€1M+",
}

state_choices = {
        'AK': 'Alaska',
        'AL': 'Alabama',
        'AR': 'Arkansas',
        'AS': 'American Samoa',
        'AZ': 'Arizona',
        'CA': 'California',
        'CO': 'Colorado',
        'CT': 'Connecticut',
        'DC': 'District of Columbia',
        'DE': 'Delaware',
        'FL': 'Florida',
        'GA': 'Georgia',
        'GU': 'Guam',
        'HI': 'Hawaii',
        'IA': 'Iowa',
        'ID': 'Idaho',
        'IL': 'Illinois',
        'IN': 'Indiana',
        'KS': 'Kansas',
        'KY': 'Kentucky',
        'LA': 'Louisiana',
        'MA': 'Massachusetts',
        'MD': 'Maryland',
        'ME': 'Maine',
        'MI': 'Michigan',
        'MN': 'Minnesota',
        'MO': 'Missouri',
        'MP': 'Northern Mariana Islands',
        'MS': 'Mississippi',
        'MT': 'Montana',
        'NA': 'National',
        'NC': 'North Carolina',
        'ND': 'North Dakota',
        'NE': 'Nebraska',
        'NH': 'New Hampshire',
        'NJ': 'New Jersey',
        'NM': 'New Mexico',
        'NV': 'Nevada',
        'NY': 'New York',
        'OH': 'Ohio',
        'OK': 'Oklahoma',
        'OR': 'Oregon',
        'PA': 'Pennsylvania',
        'PR': 'Puerto Rico',
        'RI': 'Rhode Island',
        'SC': 'South Carolina',
        'SD': 'South Dakota',
        'TN': 'Tennessee',
        'TX': 'Texas',
        'UT': 'Utah',
        'VA': 'Virginia',
        'VI': 'Virgin Islands',
        'VT': 'Vermont',
        'WA': 'Washington',
        'WI': 'Wisconsin',
        'WV': 'West Virginia',
        'WY': 'Wyoming',
        'AB': 'Alberta',
        'BC': 'British Columbia',
        'MB': 'Manitoba',
        'NB': 'New Brunswick',
        'NL': 'Newfoundland and Labrador',
        'NT': 'Northwest Territories',
        'NS': 'Nova Scotia',
        'NU': 'Nunavut',
        'ON': 'Ontario',
        'PE': 'Prince Edward Island',
        'QC': 'Quebec',
        'SK': 'Saskatchewan',
        'YT': 'Yukon',
        "BE-BRU": "Région de Bruxelles-Capitale",
        "BE-VAN": "Antwerpen", 
        "BE-WBR": "Brabant wallon",
        "BE-WHT": "Hainaut",
        "BE-WLG": "Liège",
        "BE-VLI": "Limburg",
        "BE-WLX": "Luxembourg",
        "BE-WNA": "Namur",
        "BE-VOV": "Oost-Vlaanderen",
        "BE-VBR": "Vlaams-Brabant",
        "BE-VWV": "West-Vlaanderen",
        "ES.AN": "Andalusia", 
        "ES.AR": "Aragon",
        "ES.AS": "Asturias",
        "ES.PM": "Balearic Islands",
        "ES.PV": "Basque Country",
        "ES.CN": "Canary Islands",
        "ES.CB": "Cantabria",
        "ES.CL": "Castile and Leon",
        "ES.CM": "Castile-La Mancha",
        "ES.CT": "Catalonia",
        "ES.CE": "Ceuta",
        "ES.EX": "Extremadura",
        "ES.GA": "Galicia",
        "ES.LO": "La Rioja",
        "ES.MD": "Madrid",
        "ES.ML": "Melilla",
        "ES.MU": "Murcia",
        "ES.NA": "Navarra",
        "ES.VC": "Valencia",
        "PT-01": "Aveiro", 
        "PT-02": "Beja", 
        "PT-03": "Braga", 
        "PT-04": "Bragança", 
        "PT-05": "Castelo Branco", 
        "PT-06": "Coimbra", 
        "PT-07": "Évora", 
        "PT-08": "Faro", 
        "PT-09": "Guarda", 
        "PT-10": "Leiria", 
        "PT-11": "Lisboa", 
        "PT-12": "Portalegre", 
        "PT-13": "Porto", 
        "PT-14": "Santarém", 
        "PT-15": "Setúbal", 
        "PT-16": "Viana do Castelo", 
        "PT-17": "Vila Real", 
        "PT-18": "Viseu", 
        "PT-20": "Região Autónoma dos Açores",
        "PT-30": "Região Autónoma da Madeira",
        "GR-A": "Eastern Macedonia and Thrace",
        "GR-I": "Attica", 
        "GR-G": "Western Greece",
        "GR-C": "Western Macedonia",
        "GR-F": "Ionian Islands",
        "GR-D": "Epirus",
        "GR-B": "Central Macedonia",
        "GR-M": "Crete",
        "GR-L": "Southern Aegean",
        "GR-J": "Peloponnese",
        "GR-H": "Central Greece",
        "GR-E": "Thessaly",
        "GR-K": "Northern Aegean",
}

